/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fashionflairboutique.views;

/**
 *
 * @author Chethiya
 */
public class Discounts extends javax.swing.JFrame {

    /**
     * Creates new form Discounts
     */
    public Discounts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActiveCamps = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBtnDeactivate = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jBtnCancel = new javax.swing.JButton();
        jTFPromoName = new javax.swing.JTextField();
        jDateChooserEnd = new com.toedter.calendar.JDateChooser();
        jDateChooserStart = new com.toedter.calendar.JDateChooser();
        jCBStatus = new javax.swing.JComboBox<>();
        jTFDiscountPct = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTADescription = new javax.swing.JTextArea();
        jBtnSave = new javax.swing.JButton();
        jBtnSave2 = new javax.swing.JButton();
        jCBTargetGroup = new javax.swing.JComboBox<>();
        jCBCategories = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Aarvark Cafe", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 192, 223));
        jLabel2.setText("Manage Discounts and Promotions");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 80));

        jLabel12.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel12.setText("Description :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, -1, -1));

        jTableActiveCamps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Promo ID", "Name", "Discount %", "Start Date", "End Date", "Status", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableActiveCamps);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 1140, 140));

        jLabel13.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel13.setText("Active Campaigns");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel14.setText("Campaign Details");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel15.setText("Select Catagory  for the Promo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jBtnDeactivate.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jBtnDeactivate.setText("Deactivate Selected Promo");
        jPanel1.add(jBtnDeactivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 780, -1, 40));

        jLabel16.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel16.setText("Target Group :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, -1, -1));

        jLabel17.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel17.setText("Promotion Name :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel18.setText("Discount % :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        jLabel19.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel19.setText("Start Date :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        jLabel20.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel20.setText("End Date :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        jLabel21.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel21.setText("Status :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, -1, -1));

        jBtnCancel.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jBtnCancel.setText("Cancel");
        jPanel1.add(jBtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 780, -1, 40));

        jTFPromoName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFPromoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 200, -1));

        jDateChooserEnd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jDateChooserEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 200, 30));

        jDateChooserStart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jDateChooserStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 200, 30));

        jCBStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jCBStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 200, -1));

        jTFDiscountPct.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFDiscountPct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 200, -1));

        jTADescription.setColumns(20);
        jTADescription.setRows(5);
        jScrollPane3.setViewportView(jTADescription);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, -1, -1));

        jBtnSave.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jBtnSave.setText("Save and Apply Campaign");
        jPanel1.add(jBtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 780, -1, 40));

        jBtnSave2.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jBtnSave2.setText("Save and Apply Campaign");
        jPanel1.add(jBtnSave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 780, -1, 40));

        jCBTargetGroup.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jCBTargetGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 200, -1));

        jCBCategories.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jCBCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 200, -1));

        jLabel22.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel22.setText("Categories");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Category", "Target Group", "Promotion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 600, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1291, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Discounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnDeactivate;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnSave2;
    private javax.swing.JComboBox<String> jCBCategories;
    private javax.swing.JComboBox<String> jCBStatus;
    private javax.swing.JComboBox<String> jCBTargetGroup;
    private com.toedter.calendar.JDateChooser jDateChooserEnd;
    private com.toedter.calendar.JDateChooser jDateChooserStart;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTADescription;
    private javax.swing.JTextField jTFDiscountPct;
    private javax.swing.JTextField jTFPromoName;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableActiveCamps;
    // End of variables declaration//GEN-END:variables
}
