/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fashionflairboutique.views;

import fashionflairboutique.data.UserDAO;
import fashionflairboutique.models.User;
import fashionflairboutique.views.ManageProducts;
import fashionflairboutique.views.POS;
import javax.swing.JOptionPane;
import fashionflairboutique.views.PasswordReset;

/**
 *
 * @author Chethiya
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLblForgotPass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBShowPass = new javax.swing.JCheckBox();
        jBtnLogin = new javax.swing.JButton();
        jPFPassword = new javax.swing.JPasswordField();
        jTFEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 252, 246));

        jPanel1.setBackground(new java.awt.Color(255, 252, 246));
        jPanel1.setForeground(new java.awt.Color(255, 252, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Email :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 397, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Fashion Flair Boutique Logo re.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 6, -1, -1));

        jLblForgotPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblForgotPass.setText("Forgot Password?");
        jLblForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblForgotPassMouseClicked(evt);
            }
        });
        jPanel1.add(jLblForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 673, -1, -1));

        jLabel2.setFont(new java.awt.Font("Aarvark Cafe", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 192, 223));
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 292, -1, -1));

        jCBShowPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCBShowPass.setText("Show Password");
        jCBShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(jCBShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 566, -1, -1));

        jBtnLogin.setBackground(new java.awt.Color(0, 102, 255));
        jBtnLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogin.setText("Login");
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 608, 149, 47));

        jPFPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(jPFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 526, 279, -1));

        jTFEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(jTFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 427, 279, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        String email = jTFEmail.getText().trim();
        String password = new String(jPFPassword.getPassword()).trim();

        // 1. Precise Input Validation
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Email!", 
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            jTFEmail.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Password!", 
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            jPFPassword.requestFocus();
            return;
        }

        try {
            // 2. Data Access Layer Call
            fashionflairboutique.data.UserDAO userDAO = new fashionflairboutique.data.UserDAO();
            fashionflairboutique.models.User loggedInUser = userDAO.authenticateUser(email, password);

            if (loggedInUser != null) {
                JOptionPane.showMessageDialog(this, "Welcome, " + loggedInUser.getFullName() + "!",
                        "Login Successful", JOptionPane.INFORMATION_MESSAGE);

                // 3. Role-Based Navigation
                if ("Store Manager".equalsIgnoreCase(loggedInUser.getRole())) {
                    new fashionflairboutique.views.MainDashboard(loggedInUser).setVisible(true);
                } else {
                    new fashionflairboutique.views.POS(loggedInUser).setVisible(true);
                }

                // Clean single dispose call after launching target window
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Invalid credentials or inactive account.", 
                        "Login Failed", JOptionPane.ERROR_MESSAGE);
                jPFPassword.setText("");
                jPFPassword.requestFocus();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(),
                    "System Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jCBShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBShowPassActionPerformed
        if (jCBShowPass.isSelected()) {
            jPFPassword.setEchoChar((char) 0); 
            
        } else {
            jPFPassword.setEchoChar('*'); 
        }
    }//GEN-LAST:event_jCBShowPassActionPerformed

    private void jLblForgotPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblForgotPassMouseClicked
        String email = jTFEmail.getText().trim();
        PasswordReset pr = new PasswordReset(email);
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLblForgotPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JCheckBox jCBShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblForgotPass;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFEmail;
    // End of variables declaration//GEN-END:variables
}
