/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fashionflairboutique.views;

import fashionflairboutique.models.User;

/**
 *
 * @author Chethiya
 */
public class MainDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    private User currentUser;
    
    private void applyRolePermissions() {
        jLblUname.setText("Welcome, " + currentUser.getFullName() + " (" + currentUser.getRole() + ")");

        // Hide administrative options for non-managers
        if ("Sales Assistant".equalsIgnoreCase(currentUser.getRole())) {
            jBtnManageProducts.setVisible(false);
            jBtnManageDiscounts.setVisible(false);
            jBtnManageUsers.setVisible(false);
            jBtnSalesReports.setVisible(false);
            jBtnManageCategories.setVisible(false);

        }
    }
    
    public MainDashboard() {
        initComponents();
    }

    public MainDashboard(User loggedInUser) {
        initComponents();
        this.currentUser = loggedInUser;
        
        // to apply role-based UI restrictions
        applyRolePermissions();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnManageProducts = new javax.swing.JButton();
        jBtnManageUsers = new javax.swing.JButton();
        jBtnProductCatalog = new javax.swing.JButton();
        jBtnManageDiscounts = new javax.swing.JButton();
        jBtnPOS = new javax.swing.JButton();
        jBtnSalesReports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLblUname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnManageCategories = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 252, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnManageProducts.setBackground(new java.awt.Color(26, 188, 156));
        jBtnManageProducts.setFont(new java.awt.Font("Aarvark Cafe", 0, 36)); // NOI18N
        jBtnManageProducts.setForeground(new java.awt.Color(255, 255, 255));
        jBtnManageProducts.setText("Manage Products");
        jBtnManageProducts.setMinimumSize(new java.awt.Dimension(281, 54));
        jBtnManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageProductsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnManageProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 310, 100));

        jBtnManageUsers.setBackground(new java.awt.Color(142, 68, 173));
        jBtnManageUsers.setFont(new java.awt.Font("Aarvark Cafe", 0, 36)); // NOI18N
        jBtnManageUsers.setForeground(new java.awt.Color(255, 255, 255));
        jBtnManageUsers.setText("Manage Users");
        jBtnManageUsers.setMinimumSize(new java.awt.Dimension(281, 54));
        jBtnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageUsersActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 310, 100));

        jBtnProductCatalog.setBackground(new java.awt.Color(52, 152, 219));
        jBtnProductCatalog.setFont(new java.awt.Font("Aarvark Cafe", 0, 36)); // NOI18N
        jBtnProductCatalog.setForeground(new java.awt.Color(255, 255, 255));
        jBtnProductCatalog.setText("Product Catalog");
        jBtnProductCatalog.setMinimumSize(new java.awt.Dimension(281, 54));
        jBtnProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProductCatalogActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnProductCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 310, 100));

        jBtnManageDiscounts.setBackground(new java.awt.Color(230, 126, 34));
        jBtnManageDiscounts.setFont(new java.awt.Font("Aarvark Cafe", 0, 36)); // NOI18N
        jBtnManageDiscounts.setForeground(new java.awt.Color(255, 255, 255));
        jBtnManageDiscounts.setText("Manage Discounts");
        jBtnManageDiscounts.setMinimumSize(new java.awt.Dimension(281, 54));
        jBtnManageDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageDiscountsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnManageDiscounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 310, 100));

        jBtnPOS.setBackground(new java.awt.Color(46, 204, 113));
        jBtnPOS.setFont(new java.awt.Font("Aarvark Cafe", 0, 36)); // NOI18N
        jBtnPOS.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPOS.setText("POS");
        jBtnPOS.setMinimumSize(new java.awt.Dimension(281, 54));
        jBtnPOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPOSActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 310, 100));

        jBtnSalesReports.setBackground(new java.awt.Color(52, 73, 94));
        jBtnSalesReports.setFont(new java.awt.Font("Aarvark Cafe", 0, 36)); // NOI18N
        jBtnSalesReports.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalesReports.setText("Sales Reports");
        jBtnSalesReports.setMinimumSize(new java.awt.Dimension(281, 54));
        jBtnSalesReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalesReportsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSalesReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 310, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Fashion Flair Boutique Logo re.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLblUname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jLblUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 450, 30));

        jLabel2.setFont(new java.awt.Font("Aarvark Cafe", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 192, 223));
        jLabel2.setText("Main Dashboard");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, 80));

        jBtnManageCategories.setBackground(new java.awt.Color(0, 180, 218));
        jBtnManageCategories.setFont(new java.awt.Font("Aarvark Cafe", 0, 36)); // NOI18N
        jBtnManageCategories.setForeground(new java.awt.Color(255, 255, 255));
        jBtnManageCategories.setText("Manage Categories");
        jBtnManageCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageCategoriesActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnManageCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, 310, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageProductsActionPerformed
        ManageProducts mp = new ManageProducts(currentUser);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnManageProductsActionPerformed

    private void jBtnProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProductCatalogActionPerformed
        ProductCatalog pv = new ProductCatalog(currentUser);
        pv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnProductCatalogActionPerformed

    private void jBtnPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPOSActionPerformed
        POSFrame pos = new POSFrame(currentUser);
        pos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnPOSActionPerformed

    private void jBtnSalesReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalesReportsActionPerformed
        SalesReportsFrame spf = new SalesReportsFrame(currentUser);
        spf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnSalesReportsActionPerformed

    private void jBtnManageDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageDiscountsActionPerformed
        DiscountsFrame df = new DiscountsFrame(currentUser);
        df.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnManageDiscountsActionPerformed

    private void jBtnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageUsersActionPerformed
        ManageUser mu = new ManageUser(currentUser);
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnManageUsersActionPerformed

    private void jBtnManageCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageCategoriesActionPerformed
        ManageCategories mc = new ManageCategories(currentUser);
        mc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnManageCategoriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnManageCategories;
    private javax.swing.JButton jBtnManageDiscounts;
    private javax.swing.JButton jBtnManageProducts;
    private javax.swing.JButton jBtnManageUsers;
    private javax.swing.JButton jBtnPOS;
    private javax.swing.JButton jBtnProductCatalog;
    private javax.swing.JButton jBtnSalesReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblUname;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
