/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fashionflairboutique.views;

import fashionflairboutique.data.CategoryDAO;
import fashionflairboutique.models.Category;
import fashionflairboutique.models.User;
import fashionflairboutique.utils.UIUtils;
import fashionflairboutique.views.SidebarPanel;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author Chethiya
 */
public class ManageCategories extends javax.swing.JFrame {

    private User currentUser;
    private Timer clockTimer;
    private CategoryDAO categoryDAO;
    private int selectedCategoryId = -1;
    /**
     * Creates new form ManageCategories
     */
    public ManageCategories() {
        initComponents();
    }
    
    
    public ManageCategories(User loggedInUser) {
        initComponents();
        this.currentUser = loggedInUser;
        this.categoryDAO = new CategoryDAO();
        

        // 1. Setup Status ComboBox Options
        initStatusComboBox();

        // 2. Display Header Details
        if (currentUser != null) {
            UIUtils.displayUserDetails(jLblShowUser, currentUser);
        }
        this.clockTimer = UIUtils.startLiveClock(jLblShowDate, jLblShowTime);

        // 3. Load Categories into Table
        loadCategoriesTable();

        // 4. Attach Sidebar
        if (this.currentUser != null) {
            jPanelsidebarPanelContainer.removeAll();
            jPanelsidebarPanelContainer.setLayout(new BorderLayout());

            SidebarPanel sidebar = new SidebarPanel(this, currentUser);
            jPanelsidebarPanelContainer.add(sidebar, BorderLayout.CENTER);

            jPanelsidebarPanelContainer.revalidate();
            jPanelsidebarPanelContainer.repaint();
        }
    }

    private void initStatusComboBox() {
        jCBStatus.removeAllItems();
        jCBStatus.addItem("Active");
        jCBStatus.addItem("Inactive");
        jCBStatus.setSelectedIndex(0); // Default to Active
    }

    private void loadCategoriesTable() {
        try {
            List<Category> list = categoryDAO.getAllCategories();
            DefaultTableModel model = (DefaultTableModel) jTableCategories.getModel();
            model.setRowCount(0);

            for (Category cat : list) {
                model.addRow(new Object[]{
                    cat.getCategoryId(),                                       // Col 0
                    cat.getCategoryName(),                                     // Col 1
                    cat.getDescription() != null ? cat.getDescription() : "",  // Col 2
                    cat.getStatus()                                            // Col 3
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading categories: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void clearForm() {
        selectedCategoryId = -1;
        jTFCName.setText("");
        jTADescription.setText("");
        jCBStatus.setSelectedIndex(0); // Reset to "Active"
        jTableCategories.clearSelection();
    }

    @Override
    public void dispose() {
        if (clockTimer != null && clockTimer.isRunning()) {
            clockTimer.stop();
        }
        super.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelsidebarPanelContainer = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLblShowUser = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLblShowDate = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLblShowTime = new javax.swing.JLabel();
        jLblMessage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFCName = new javax.swing.JTextField();
        jBtnAdd = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescription = new javax.swing.JTextArea();
        jCBStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCategories = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 252, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelsidebarPanelContainer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelsidebarPanelContainer.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanelsidebarPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 730));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("User :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLblShowUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblShowUser.setText("User :");
        jPanel1.add(jLblShowUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 380, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Date :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLblShowDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblShowDate.setText("User :");
        jPanel1.add(jLblShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 290, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Time :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLblShowTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblShowTime.setText("User :");
        jPanel1.add(jLblShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 220, -1));

        jLblMessage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jLblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 860, 40));

        jLabel3.setFont(new java.awt.Font("Aarvark Cafe", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(12, 192, 223));
        jLabel3.setText("Manage Categories");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Status :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        jTFCName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 300, -1));

        jBtnAdd.setBackground(new java.awt.Color(46, 204, 113));
        jBtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 90, 40));

        jBtnUpdate.setBackground(new java.awt.Color(52, 152, 219));
        jBtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, 40));

        jBtnClear.setBackground(new java.awt.Color(127, 140, 141));
        jBtnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBtnClear.setText("Clear");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 90, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Category Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Desciption :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jTADescription.setColumns(20);
        jTADescription.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTADescription.setRows(5);
        jScrollPane1.setViewportView(jTADescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 300, -1));

        jCBStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jCBStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 200, 40));

        jTableCategories.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Category Name", "Description", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCategoriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCategories);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        String name = jTFCName.getText().trim();
        String description = jTADescription.getText().trim();

        // Safely get status from JComboBox
        String status = jCBStatus.getSelectedItem() != null ? jCBStatus.getSelectedItem().toString() : "Active";

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Category Name is required!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (categoryDAO.categoryNameExists(name, -1)) {
                JOptionPane.showMessageDialog(this, "Category name already exists!", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Saves name, description, and status to Database
            if (categoryDAO.addCategory(name, description, status)) {
                JOptionPane.showMessageDialog(this, "Category added successfully!");
                clearForm();
                loadCategoriesTable(); // Reloads table to display status in Col 3
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to add category: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        if (selectedCategoryId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a category from the table to update.", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String name = jTFCName.getText().trim();
        String description = jTADescription.getText().trim();
        String status = jCBStatus.getSelectedItem().toString(); // Reads selected value from JComboBox

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Category Name cannot be empty!", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (categoryDAO.categoryNameExists(name, selectedCategoryId)) {
                JOptionPane.showMessageDialog(this, "Another category with this name already exists!", "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (categoryDAO.updateCategory(selectedCategoryId, name, description, status)) {
                JOptionPane.showMessageDialog(this, "Category updated successfully!");
                clearForm();
                loadCategoriesTable();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to update category: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jTableCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCategoriesMouseClicked
        int selectedRow = jTableCategories.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) jTableCategories.getModel();
            selectedCategoryId = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());
            jTFCName.setText(model.getValueAt(selectedRow, 1).toString());
            jTADescription.setText(model.getValueAt(selectedRow, 2).toString());

            // Select matching item in JComboBox
            String status = model.getValueAt(selectedRow, 3).toString();
            jCBStatus.setSelectedItem(status);
        }
    }//GEN-LAST:event_jTableCategoriesMouseClicked

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_jBtnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JComboBox<String> jCBStatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblMessage;
    private javax.swing.JLabel jLblShowDate;
    private javax.swing.JLabel jLblShowTime;
    private javax.swing.JLabel jLblShowUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelsidebarPanelContainer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescription;
    private javax.swing.JTextField jTFCName;
    private javax.swing.JTable jTableCategories;
    // End of variables declaration//GEN-END:variables
}
