/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fashionflairboutique.views;

import fashionflairboutique.data.ProductDAO;
import fashionflairboutique.data.POSDAO;
import fashionflairboutique.data.ProductCatalogDAO;
import fashionflairboutique.models.POS;
import fashionflairboutique.utils.UIUtils;
import fashionflairboutique.models.Product;
import fashionflairboutique.models.User;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Chethiya
 */
public class POSFrame extends javax.swing.JFrame {

    /**
     * Creates new form POSFrame
     */
    private User currentUser;
    private Timer clockTimer;
    private POS currentScannedProduct = null;
    private int selectedCartRow = -1;
    private double cartSubtotal = 0.0;
    private double customerDiscountAmount = 0.0;
    private double grandTotal = 0.0;
    
    public POSFrame() {
        initComponents();
    }
    
    public POSFrame(User loggedInUser) {
        initComponents(); // Initializes GUI components generated by NetBeans
        this.currentUser = loggedInUser;
        ((DefaultTableModel) jTableCart.getModel()).setRowCount(0);
        loadPaymentMethodComboBox();
        
        UIUtils.displayUserDetails(jLblShowUser, currentUser);
        this.clockTimer = UIUtils.startLiveClock(jLblShowDate, jLblShowTime);
        
        // Example: Display the logged-in user's name on the title bar or a label
        this.setTitle("Fashion Flair Boutique - Manage Products (" + currentUser.getFullName() + ")");
        
        jTFBarcode.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAndPopulateProduct();
            }
        });
        
        jTableCart.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting() && jTableCart.getSelectedRow() != -1) {
                populateFieldsFromCartRow();
            }
        });
        
    }
    
    private void loadPaymentMethodComboBox() {
        jCBPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[]{"Cash", "Credit Card", "Debit Card"}
        ));
    }
    
    private void applyCustomerDiscount() {
        double discountPercentage;
        try {
            String text = jTFDiscount.getText().trim();
            discountPercentage = text.isEmpty() ? 0.0 : Double.parseDouble(text);
            if (discountPercentage < 0 || discountPercentage > 100) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Enter a valid discount percentage (0-100).",
//                "Input Error", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Enter a valid discount percentage (0-100)!");
            jTFDiscount.setText("0");
            discountPercentage = 0.0;
        }

        customerDiscountAmount = cartSubtotal * (discountPercentage / 100.0);
        grandTotal = cartSubtotal - customerDiscountAmount;

        jTFTotal.setText(String.format("%.2f", grandTotal));
    }
    
    private void recalculateCartTotal() {
        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
        double subtotal = 0.0;
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 6); // lineTotal column
            if (value != null) {
                subtotal += Double.parseDouble(value.toString());
            }
        }
        cartSubtotal = subtotal;
        jTFSubTotal.setText(String.format("%.2f", cartSubtotal));

        applyCustomerDiscount(); // keep the grand total in sync every time the cart changes
    }
      
    private void searchAndPopulateProduct() {
        String barcodeText = jTFBarcode.getText().trim();

        if (barcodeText.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Please enter a barcode.", "Warning", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Please enter a barcode!");
            return;
        }

        POSDAO posDAO = new POSDAO();
        POS pos = posDAO.getProductByBarcode(barcodeText);

        if (pos != null) {
            // Populate the UI text fields matching your form elements
            currentScannedProduct = pos;  
            jTFPName.setText(pos.getProductName());
            jTFPrice.setText(String.format("%.2f", pos.getPrice()));
            jTFAvailableQty.setText(String.valueOf(pos.getAvailableQty()));

            // Reset quantity input to 1 and shift focus to quantity field
            jTFQty.setText("");
            jTFQty.requestFocus();
        } else {
            currentScannedProduct = null;
//            JOptionPane.showMessageDialog(this, "Product not found!", "Search Error", JOptionPane.ERROR_MESSAGE);
            UIUtils.showError(jLblMessage, "Product not found!");
            clearProductFields();
            jTFBarcode.requestFocus();
        }
    }
    
    private void addProductDetailsToTable(POS pos, int qty) {
        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();

        double unitPrice = pos.getPrice();
        double discountPercentage = pos.getDiscount();
        double discountPerUnit = unitPrice * (discountPercentage / 100.0);
        double totalDiscount = discountPerUnit * qty;          // scales with quantity
        double lineTotal = (unitPrice * qty) - totalDiscount;  // equivalent to discountedUnitPrice * qty

        model.addRow(new Object[]{
            pos.getProductId(),
            pos.getBarcode(),
            pos.getProductName(),
            qty,
            unitPrice,
            totalDiscount,   // was just discountPercentage - now the actual currency amount for the whole line
            lineTotal
        });
    }
    
    private void populateFieldsFromCartRow() {
        selectedCartRow = jTableCart.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();

        String barcode = model.getValueAt(selectedCartRow, 1).toString();
        String productName = model.getValueAt(selectedCartRow, 2).toString();
        int qty = Integer.parseInt(model.getValueAt(selectedCartRow, 3).toString());

        // Re-fetch the product so we know current stock (the cart row itself
        // doesn't store availableQty - only productId/barcode/name/qty/price/total)
        POSDAO posDAO = new POSDAO();
        POS pos = posDAO.getProductByBarcode(barcode);

        if (pos != null) {
            currentScannedProduct = pos;
            jTFBarcode.setText(barcode);
            jTFPName.setText(productName);
            jTFPrice.setText(String.format("%.2f", pos.getPrice()));
            jTFAvailableQty.setText(String.valueOf(pos.getAvailableQty()));
            jTFQty.setText(String.valueOf(qty)); // pre-fill with the cart's current quantity
        }
    }
    
    private int findCartRowByProductId(int productId) {
        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            int rowProductId = Integer.parseInt(model.getValueAt(i, 0).toString());
            if (rowProductId == productId) {
                return i;
            }
        }
        return -1;
    }

    private void clearProductFields() {
        jTFBarcode.setText("");
        jTFPName.setText("");
        jTFPrice.setText("");
        jTFAvailableQty.setText("");
        jTFQty.setText("");
        
        
    }
    
    private void resetCartSelectionState() {
        selectedCartRow = -1;
        currentScannedProduct = null;
        clearProductFields();
        jTableCart.clearSelection();
        jTFSubTotal.setText("");
        jTFTotal.setText("");
    }
    
//    private void clearAll(){
//        clearProductFields();
//        resetCartSelectionState();
//        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
//        model.setRowCount(0);
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLblShowTime = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLblShowUser = new javax.swing.JLabel();
        jLblShowDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCart = new javax.swing.JTable();
        jLblMessage = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTFBarcode = new javax.swing.JTextField();
        jTFPName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTFPrice = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTFAvailableQty = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTFQty = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTFTotal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jBtnCheckOut = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnRemove = new javax.swing.JButton();
        jBtnClearTable = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTFPaidAmount = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTFChange = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTFDiscount = new javax.swing.JTextField();
        jCBPaymentMethod = new javax.swing.JComboBox<>();
        jTFSubTotal = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Aarvark Cafe", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 192, 223));
        jLabel2.setText("POS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, 130, -1));

        jLblShowTime.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLblShowTime.setText("User :");
        jPanel1.add(jLblShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 220, -1));

        jLabel17.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel17.setText("Date  :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel18.setText("Time :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel19.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel19.setText("User :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLblShowUser.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLblShowUser.setText("User :");
        jPanel1.add(jLblShowUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 290, -1));

        jLblShowDate.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLblShowDate.setText("User :");
        jPanel1.add(jLblShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 290, -1));

        jTableCart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Barcode", "Product Name", "Quantity", "Unit Price", "Discount %", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCart);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 1090, 530));

        jLblMessage.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jPanel1.add(jLblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 720, 40));

        jLabel20.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel20.setText("Barcode");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jTFBarcode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 300, -1));

        jTFPName.setEditable(false);
        jTFPName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFPName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 300, -1));

        jLabel21.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel21.setText("Product Name :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jTFPrice.setEditable(false);
        jTFPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 300, -1));

        jLabel22.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel22.setText("Price :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jTFAvailableQty.setEditable(false);
        jTFAvailableQty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFAvailableQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 300, -1));

        jLabel23.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel23.setText("Available Stock Quantity :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jTFQty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(jTFQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 300, -1));

        jLabel24.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel24.setText("Qty :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        jTFTotal.setEditable(false);
        jTFTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel1.add(jTFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 810, 300, -1));

        jLabel25.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel25.setText("Total :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 780, -1, -1));

        jBtnCheckOut.setBackground(new java.awt.Color(0, 102, 255));
        jBtnCheckOut.setFont(new java.awt.Font("Aarvark Cafe", 0, 48)); // NOI18N
        jBtnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCheckOut.setText("CheckOut");
        jBtnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 810, 380, 140));

        jBtnAdd.setBackground(new java.awt.Color(0, 102, 255));
        jBtnAdd.setFont(new java.awt.Font("Aarvark Cafe", 0, 22)); // NOI18N
        jBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 120, 50));

        jBtnUpdate.setBackground(new java.awt.Color(0, 102, 255));
        jBtnUpdate.setFont(new java.awt.Font("Aarvark Cafe", 0, 22)); // NOI18N
        jBtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUpdate.setText("Update");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 120, 50));

        jBtnRemove.setBackground(new java.awt.Color(0, 102, 255));
        jBtnRemove.setFont(new java.awt.Font("Aarvark Cafe", 0, 22)); // NOI18N
        jBtnRemove.setForeground(new java.awt.Color(255, 255, 255));
        jBtnRemove.setText("Remove");
        jBtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 110, 50));

        jBtnClearTable.setBackground(new java.awt.Color(0, 102, 255));
        jBtnClearTable.setFont(new java.awt.Font("Aarvark Cafe", 0, 22)); // NOI18N
        jBtnClearTable.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClearTable.setText("Clear Table");
        jBtnClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearTableActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnClearTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 330, 70));

        jLabel26.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel26.setText("Paid :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 880, -1, -1));

        jTFPaidAmount.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFPaidAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPaidAmountActionPerformed(evt);
            }
        });
        jPanel1.add(jTFPaidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 910, 300, -1));

        jLabel27.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel27.setText("Change :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 880, -1, -1));

        jTFChange.setEditable(false);
        jTFChange.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel1.add(jTFChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 910, 300, -1));

        jLabel28.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel28.setText("Payment Method :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 880, -1, -1));

        jLabel29.setFont(new java.awt.Font("Aarvark Cafe", 0, 18)); // NOI18N
        jLabel29.setText("Discount  Pct :");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 780, -1, -1));

        jTFDiscount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDiscountActionPerformed(evt);
            }
        });
        jPanel1.add(jTFDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 810, 300, 40));

        jCBPaymentMethod.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel1.add(jCBPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 910, 300, 40));

        jTFSubTotal.setEditable(false);
        jTFSubTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel1.add(jTFSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 810, 300, -1));

        jLabel30.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel30.setText("Sub Total :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 780, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCheckOutActionPerformed
        if (jTableCart.getRowCount() == 0) {
//            JOptionPane.showMessageDialog(this, "Cart is empty.", "Warning", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Cart is empty!");
            return;
        }

        String paymentMethod = jCBPaymentMethod.getSelectedItem().toString();
        DefaultTableModel cartModel = (DefaultTableModel) jTableCart.getModel();

        POSDAO posDAO = new POSDAO();
        if (posDAO.processSale(currentUser.getUserId(), paymentMethod, cartModel, customerDiscountAmount)) {
//            JOptionPane.showMessageDialog(this, "Sale completed!", "Success", JOptionPane.INFORMATION_MESSAGE);
            UIUtils.showSuccess(jLblMessage, "Sale completed!");
            cartModel.setRowCount(0);
            clearProductFields();
            jTFDiscount.setText("0");
            cartSubtotal = 0.0;
            customerDiscountAmount = 0.0;
            grandTotal = 0.0;
            jTFSubTotal.setText("0.00");
            jTFTotal.setText("0.00");
        } else {
//            JOptionPane.showMessageDialog(this, "Checkout failed - transaction rolled back.",
//                "Error", JOptionPane.ERROR_MESSAGE);
            UIUtils.showError(jLblMessage, "Checkout failed - transaction rolled back!");
        }
    }//GEN-LAST:event_jBtnCheckOutActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        
//        if (selectedCartRow != -1) {
//            JOptionPane.showMessageDialog(this,
//                "A cart row is selected - click Update or Delete, or clear the selection before adding a new item.",
//                "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }

        if (currentScannedProduct == null) {
//            JOptionPane.showMessageDialog(this, "Scan or search a product first.", "Warning", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Scan or search a product first!");
            return;
        }

        int qty;
        try {
            qty = Integer.parseInt(jTFQty.getText().trim());
            if (qty <= 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Enter a valid quantity.", "Input Error", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Enter a valid quantity!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
        int existingRow = findCartRowByProductId(currentScannedProduct.getProductId());

        if (existingRow != -1) {
            // Product already in cart - merge quantities instead of duplicating the row
            int existingQty = Integer.parseInt(model.getValueAt(existingRow, 3).toString());
            int combinedQty = existingQty + qty;

            if (combinedQty > currentScannedProduct.getAvailableQty()) {
//                JOptionPane.showMessageDialog(this,
//                    "Not enough stock. Already have " + existingQty + " in cart, available: " +
//                    currentScannedProduct.getAvailableQty(),
//                    "Insufficient Stock", JOptionPane.WARNING_MESSAGE);
                UIUtils.showError(jLblMessage, "Not enough stock. Already have " + existingQty + " in cart, available: " +
                    currentScannedProduct.getAvailableQty() + " - Insufficient Stock");
                return;
            }

            double unitPrice = currentScannedProduct.getPrice();
            double discountPercentage = currentScannedProduct.getDiscount();
            double discountPerUnit = unitPrice * (discountPercentage / 100.0);
            double totalDiscount = discountPerUnit * combinedQty;              // recalculated for combined qty
            double newLineTotal = (unitPrice * combinedQty) - totalDiscount;

            model.setValueAt(combinedQty, existingRow, 3);
            model.setValueAt(unitPrice, existingRow, 4);
            model.setValueAt(totalDiscount, existingRow, 5);
            model.setValueAt(newLineTotal, existingRow, 6);

        } else {
            // New product for this cart
            if (qty > currentScannedProduct.getAvailableQty()) {
//                JOptionPane.showMessageDialog(this,
//                    "Not enough stock. Available: " + currentScannedProduct.getAvailableQty(),
//                    "Insufficient Stock", JOptionPane.WARNING_MESSAGE);
                UIUtils.showError(jLblMessage, "Not enough stock. Available: " + currentScannedProduct.getAvailableQty() +
                    " - Insufficient Stock");
                return;
            }
            addProductDetailsToTable(currentScannedProduct, qty);
        }
        
        recalculateCartTotal();
        currentScannedProduct = null;
        clearProductFields();
        jTFBarcode.setText("");
        jTFBarcode.requestFocus();
        
        selectedCartRow = -1;
        jTableCart.clearSelection();
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        if (selectedCartRow == -1) {
//            JOptionPane.showMessageDialog(this, "Select a cart row first.", "Warning", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Select a cart row first!");
            return;
        }
        if (currentScannedProduct == null) {
//            JOptionPane.showMessageDialog(this, "Product data unavailable - reselect the row.", "Warning", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Product data unavailable - reselect the row!");
            return;
        }

        int newQty;
        try {
            newQty = Integer.parseInt(jTFQty.getText().trim());
            if (newQty <= 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(this, "Enter a valid quantity.", "Input Error", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Enter a valid quantity!");
            return;
        }

        if (newQty > currentScannedProduct.getAvailableQty()) {
//            JOptionPane.showMessageDialog(this,
//                "Not enough stock. Available: " + currentScannedProduct.getAvailableQty(),
//                "Insufficient Stock", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Not enough stock. Available: " + currentScannedProduct.getAvailableQty() +
                " - Insufficient Stock");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
        double unitPrice = currentScannedProduct.getPrice();
        double discountPercentage = currentScannedProduct.getDiscount();
        double discountPerUnit = unitPrice * (discountPercentage / 100.0);
        double totalDiscount = discountPerUnit * newQty;
        double newLineTotal = (unitPrice * newQty) - totalDiscount;

        model.setValueAt(newQty, selectedCartRow, 3);
        model.setValueAt(unitPrice, selectedCartRow, 4);
        model.setValueAt(totalDiscount, selectedCartRow, 5);
        model.setValueAt(newLineTotal, selectedCartRow, 6);

        recalculateCartTotal();
        resetCartSelectionState();
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    private void jBtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoveActionPerformed
        if (selectedCartRow == -1) {
//            JOptionPane.showMessageDialog(this, "Select a cart row first.", "Warning", JOptionPane.WARNING_MESSAGE);
            UIUtils.showError(jLblMessage, "Select a cart row first!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
        model.removeRow(selectedCartRow);

        recalculateCartTotal();
        resetCartSelectionState();
    }//GEN-LAST:event_jBtnRemoveActionPerformed

    private void jBtnClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearTableActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
        model.setRowCount(0);
        resetCartSelectionState();
    }//GEN-LAST:event_jBtnClearTableActionPerformed

    private void jTFDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDiscountActionPerformed
        applyCustomerDiscount();
        jTFPaidAmount.requestFocus();
    }//GEN-LAST:event_jTFDiscountActionPerformed

    private void jTFPaidAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPaidAmountActionPerformed
        try {
            String totalText = jTFTotal.getText().trim();
            String paidText = jTFPaidAmount.getText().trim();

            if (paidText.isEmpty() || totalText.isEmpty()) {
                jTFChange.setText("");
                return;
            }

            double total = Double.parseDouble(totalText);
            double paidAmt = Double.parseDouble(paidText);

            if (paidAmt < total) {
//                JOptionPane.showMessageDialog(this, "Paid amount cannot be less than the total!", "Invalid Payment", JOptionPane.WARNING_MESSAGE);
                UIUtils.showError(jLblMessage, "Paid amount cannot be less than the total!  Invalid Payment!");
                jTFChange.setText("0.00");
                return;
            }

            double change = paidAmt - total;
            jTFChange.setText(String.format("%.2f", change));

        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Please enter a valid numeric amount.", "Format Error", JOptionPane.ERROR_MESSAGE);
            UIUtils.showError(jLblMessage, "Please enter a valid numeric amount!");
            jTFChange.setText("");
        }
    }//GEN-LAST:event_jTFPaidAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnCheckOut;
    private javax.swing.JButton jBtnClearTable;
    private javax.swing.JButton jBtnRemove;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JComboBox<String> jCBPaymentMethod;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLblMessage;
    private javax.swing.JLabel jLblShowDate;
    private javax.swing.JLabel jLblShowTime;
    private javax.swing.JLabel jLblShowUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAvailableQty;
    private javax.swing.JTextField jTFBarcode;
    private javax.swing.JTextField jTFChange;
    private javax.swing.JTextField jTFDiscount;
    private javax.swing.JTextField jTFPName;
    private javax.swing.JTextField jTFPaidAmount;
    private javax.swing.JTextField jTFPrice;
    private javax.swing.JTextField jTFQty;
    private javax.swing.JTextField jTFSubTotal;
    private javax.swing.JTextField jTFTotal;
    private javax.swing.JTable jTableCart;
    // End of variables declaration//GEN-END:variables
}
