/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fashionflairboutique.views;

import fashionflairboutique.data.SalesReportDAO;
import fashionflairboutique.models.SalesReport;
import fashionflairboutique.models.User;
import fashionflairboutique.utils.UIUtils;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chethiya
 */
public class SalesReportsFrame extends javax.swing.JFrame {

    private User currentUser;
    private Timer clockTimer;
    /**
     * Creates new form SalesReports
     */
    public SalesReportsFrame() {
        initComponents();
    }
    
    public SalesReportsFrame(User loggedInUser){
        initComponents();
        this.currentUser = loggedInUser;
        
        UIUtils.displayUserDetails(jLblShowUser, currentUser);
        this.clockTimer = UIUtils.startLiveClock(jLblShowDate, jLblShowTime);
        loadTableData();
        System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.NoOpLog");
        
        if (this.currentUser != null) {
            // 1. Set BorderLayout on your newly created side panel
            jPanelsidebarPanelContainer.setLayout(new java.awt.BorderLayout());

            // 2. Instantiate your custom SidebarPanel
            SidebarPanel sidebar = new SidebarPanel(this, currentUser);

            // 3. Add sidebar to the side panel container
            jPanelsidebarPanelContainer.add(sidebar, java.awt.BorderLayout.CENTER);

            // 4. Refresh both the container and the frame
            jPanelsidebarPanelContainer.revalidate();
            jPanelsidebarPanelContainer.repaint();
        }
    }
    
    
    private void loadTableData(){
        String[] columnNames = {"Sale ID", "Invoice No", "Cashier", "Discount", "Net Total", "Date & Time"};
        DefaultTableModel reportTable = new DefaultTableModel(columnNames, 0);

        try {
            SalesReportDAO dao = new SalesReportDAO();
            // Passing empty strings fetches all records by default
            List<SalesReport> results = dao.searchSales("", "");

            for (SalesReport sr : results) {
                Object[] row = new Object[] {
                    sr.getSaleId(),
                    sr.getInvoiceNumber(),
                    sr.getCashier(),
                    sr.getTotalDiscount(),
                    sr.getNetTotal(),
                    sr.getSaleDate()
                };
                reportTable.addRow(row);
            }

            jTable1.setModel(reportTable);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error loading sales report: " + e.getMessage(),
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
        updateSummaryLabels();
    
    }
    
    private void updateSummaryLabels() {
        // Fetch metrics directly from database via DAO
        double totalRevenue = SalesReportDAO.getTotalRevenue();
        int totalTransactions = SalesReportDAO.getTotalTransactions();
        double avgOrderValue = SalesReportDAO.getAverageOrderValue();
        int totalItemsSold = SalesReportDAO.getTotalItemsSold();

        // Set text to the UI JLabels
        jLblTotalRevenue.setText(String.format("LKR %.2f", totalRevenue));
        jLblTotalTransactions.setText(String.valueOf(totalTransactions));
        jLblAverageOrderValue.setText(String.format("LKR %.2f", avgOrderValue));
        jLblTotalItemsSold.setText(String.valueOf(totalItemsSold));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTFReferenceNo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jBtnResetSearch = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jBtnSearch = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jBtnExportExcel = new javax.swing.JButton();
        jBtnExportPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLblTotalItemsSold = new javax.swing.JLabel();
        jLblTotalRevenue = new javax.swing.JLabel();
        jLblTotalTransactions = new javax.swing.JLabel();
        jLblAverageOrderValue = new javax.swing.JLabel();
        jLblShowTime = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLblShowUser = new javax.swing.JLabel();
        jLblShowDate = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanelsidebarPanelContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 252, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Aarvark Cafe", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 192, 223));
        jLabel2.setText("Sales Reports");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, 80));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jTFReferenceNo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Select a date :");

        jDateChooser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jBtnResetSearch.setBackground(new java.awt.Color(127, 140, 141));
        jBtnResetSearch.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jBtnResetSearch.setForeground(new java.awt.Color(255, 255, 255));
        jBtnResetSearch.setText("Reset");
        jBtnResetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetSearchActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel22.setText("Search Report :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Reference No :");

        jBtnSearch.setBackground(new java.awt.Color(37, 99, 235));
        jBtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jBtnSearch.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Aarvark Cafe", 0, 24)); // NOI18N
        jLabel24.setText("Export Report :");

        jBtnExportExcel.setBackground(new java.awt.Color(37, 179, 66));
        jBtnExportExcel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jBtnExportExcel.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExportExcel.setText("Excel Sheet");
        jBtnExportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExportExcelActionPerformed(evt);
            }
        });

        jBtnExportPDF.setBackground(new java.awt.Color(174, 34, 5));
        jBtnExportPDF.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jBtnExportPDF.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExportPDF.setText("PDF");
        jBtnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExportPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtnExportPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnExportExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFReferenceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52)
                .addComponent(jBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFReferenceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExportPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 1010, 270));

        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sale ID", "Invoice No", "Cashier ", "Payment Method", "Discount", "Total Amount", "Date & Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 1370, -1));

        jLblTotalItemsSold.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblTotalItemsSold.setText("jLabel1");
        jPanel1.add(jLblTotalItemsSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 110, 300, 80));

        jLblTotalRevenue.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblTotalRevenue.setText("jLabel1");
        jPanel1.add(jLblTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 360, 70));

        jLblTotalTransactions.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblTotalTransactions.setText("jLabel1");
        jPanel1.add(jLblTotalTransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 280, 70));

        jLblAverageOrderValue.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblAverageOrderValue.setText("jLabel1");
        jPanel1.add(jLblAverageOrderValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 200, 320, 70));

        jLblShowTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblShowTime.setText("User :");
        jPanel1.add(jLblShowTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 220, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Date :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Time :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("User :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLblShowUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblShowUser.setText("User :");
        jPanel1.add(jLblShowUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 420, -1));

        jLblShowDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblShowDate.setText("User :");
        jPanel1.add(jLblShowDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 290, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setText("Total Revenue :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("Total Items Sold :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel27.setText("Average Order Value :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("Total  Transactions :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jPanelsidebarPanelContainer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanelsidebarPanelContainer.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanelsidebarPanelContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 1090));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
       
        String invoiceInput = jTFReferenceNo.getText();
        String dateInput = "";

        // Safely extract date if selected from JDateChooser
        if (jDateChooser.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dateInput = sdf.format(jDateChooser.getDate());
        }

        // 1. Define your table column headers
        String[] columnNames = {"Sale ID", "Invoice No", "Cashier", "Discount", "Net Total", "Date & Time"};

        // 2. Initialize the table model with the column headers
        DefaultTableModel reportTable = new DefaultTableModel(columnNames, 0);

        try {
            SalesReportDAO dao = new SalesReportDAO();
            List<SalesReport> results = dao.searchSales(invoiceInput, dateInput);

            // 3. Loop through each result and add rows to the model
            for (SalesReport sr : results) {
                Object[] row = new Object[] {
                    sr.getSaleId(),
                    sr.getInvoiceNumber(),
                    sr.getCashier(),
                    sr.getTotalDiscount(),
                    sr.getNetTotal(),
                    sr.getSaleDate()
                };
                reportTable.addRow(row);
            }

            // 4. CRITICAL: Set the populated model to your actual JTable on the form
            jTable1.setModel(reportTable);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error loading sales report: " + e.getMessage(),
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jBtnResetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetSearchActionPerformed
        // Clear reference no
        jTFReferenceNo.setText("");
    
        // Clear the date picker selection
        jDateChooser.setDate(null);

        // Reload the full table data
        loadTableData();
    }//GEN-LAST:event_jBtnResetSearchActionPerformed

    private void jBtnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExportPDFActionPerformed
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No sales data available in the table to export!", "Export Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save PDF Sales Report");
        fileChooser.setSelectedFile(new java.io.File("SalesReport.pdf"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();

            // Ensure .pdf extension
            if (!fileToSave.getAbsolutePath().endsWith(".pdf")) {
                fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".pdf");
            }

            try {
                fashionflairboutique.utils.ReportExporterPDF.exportToPDF(jTable1, fileToSave);
                JOptionPane.showMessageDialog(this, "PDF report exported successfully:\n" + fileToSave.getAbsolutePath(), "Export Complete", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage(), "Export Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jBtnExportPDFActionPerformed

    private void jBtnExportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExportExcelActionPerformed
        if (jTable1.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No sales data available in the table to export!", "Export Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Excel Sales Report");
        fileChooser.setSelectedFile(new java.io.File("SalesReport.xlsx"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();

            // Ensure .xlsx extension
            if (!fileToSave.getAbsolutePath().endsWith(".xlsx")) {
                fileToSave = new java.io.File(fileToSave.getAbsolutePath() + ".xlsx");
            }

            try {
                fashionflairboutique.utils.ReportExporterExcel.exportToExcel(jTable1, fileToSave);
                JOptionPane.showMessageDialog(this, "Excel report exported successfully:\n" + fileToSave.getAbsolutePath(), "Export Complete", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generating Excel file: " + e.getMessage(), "Export Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jBtnExportExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReportsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReportsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExportExcel;
    private javax.swing.JButton jBtnExportPDF;
    private javax.swing.JButton jBtnResetSearch;
    private javax.swing.JButton jBtnSearch;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLblAverageOrderValue;
    private javax.swing.JLabel jLblShowDate;
    private javax.swing.JLabel jLblShowTime;
    private javax.swing.JLabel jLblShowUser;
    private javax.swing.JLabel jLblTotalItemsSold;
    private javax.swing.JLabel jLblTotalRevenue;
    private javax.swing.JLabel jLblTotalTransactions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelsidebarPanelContainer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFReferenceNo;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
