/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fashionflairboutique.views;

import fashionflairboutique.models.User;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.net.URL;

/**
 *
 * @author Chethiya
 */
public class SidebarPanel extends javax.swing.JPanel {

   private final JFrame parentFrame;
    private final User currentUser;

    public SidebarPanel(JFrame parentFrame, User currentUser) {
        this.parentFrame = parentFrame;
        this.currentUser = currentUser;

        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setBackground(new Color(45, 52, 54)); // Dark theme sidebar
        setPreferredSize(new Dimension(220, 0));
        setBorder(BorderFactory.createEmptyBorder(20, 10, 20, 10));

        buildMenu();
    }
    
    private void buildMenu() {
        String role = currentUser.getRole(); // e.g., "Admin", "Boutique Manager", "Cashier"

        // --- COMMON LINKS (ALL ROLES) ---
        addNavButton("Dashboard", "/resources/home.png", e -> navigateTo(new MainDashboard(currentUser)));
        addNavButton("POS / Sales", "/resources/pos.png", e -> navigateTo(new POSFrame(currentUser)));
        addNavButton("Product Catalog", "/resources/product-catalog.png", e -> navigateTo(new ProductCatalog(currentUser)));

        // --- MANAGER ONLY ---
        if ("Boutique Manager".equalsIgnoreCase(role)) {
            addNavButton("User Management","/resources/user.png" ,e -> navigateTo(new ManageUser(currentUser)));
            addNavButton("Sales Reports", "/resources/report.png", e -> navigateTo(new SalesReportsFrame(currentUser)));
            addNavButton("Manage Products", "/resources/product.png", e -> navigateTo(new ManageProducts(currentUser)));
            addNavButton("Discounts & Promos", "/resources/discount.png", e -> navigateTo(new DiscountsFrame(currentUser)));
        }

        // --- LOGOUT (ALL ROLES) ---
        add(Box.createVerticalGlue()); // Push logout to bottom
        addNavButton("Logout", "/resources/logout.png", e -> {
            int confirm = JOptionPane.showConfirmDialog(
                parentFrame, 
                "Are you sure you want to log out?", 
                "Logout", 
                JOptionPane.YES_NO_OPTION
            );
            if (confirm == JOptionPane.YES_OPTION) {
                parentFrame.dispose();
                new Login().setVisible(true);
            }
        });
    }

    private void addNavButton(String text, String iconPath, ActionListener action) {
        JButton button = new JButton(text);

        // Safely load and scale icon (20x20 pixels)
        try {
            URL imgURL = getClass().getResource(iconPath);
            if (imgURL != null) {
                ImageIcon originalIcon = new ImageIcon(imgURL);
                Image scaledImg = originalIcon.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
                button.setIcon(new ImageIcon(scaledImg));
            } else {
                System.err.println("Icon missing: " + iconPath);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Button Layout & Appearance
        button.setIconTextGap(12);
        button.setHorizontalAlignment(SwingConstants.LEFT);
        button.setMaximumSize(new Dimension(Integer.MAX_VALUE, 42));
        button.setAlignmentX(Component.CENTER_ALIGNMENT);
        button.setFocusPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Styling
        button.setBackground(new Color(45, 52, 54));
        button.setForeground(Color.WHITE);
        button.setFont(new Font("SansSerif", Font.BOLD, 13));
        button.setBorder(BorderFactory.createEmptyBorder(8, 12, 8, 12));

        // Mouse Hover Effects
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(new Color(99, 110, 114));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(new Color(45, 52, 54));
            }
        });

        button.addActionListener(action);

        add(button);
        add(Box.createRigidArea(new Dimension(0, 8))); // Vertical spacing
    }

    private void navigateTo(JFrame targetFrame) {
        parentFrame.dispose();
        targetFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
